--CREATE TABLE VegAndFr
--(
--	Id INT PRIMARY KEY NOT NULL IDENTITY,
--	[Name] NVARCHAR(100) NOT NULL,
--	[Type] NVARCHAR(100) NOT NULL,
--	Color NVARCHAR(100) NOT NULL,
--	Calories INT NOT NULL CHECK(Calories > 0)
--)

--INSERT INTO VegAndFr([Name], [Type], Color, Calories)
--VALUES(N'моркрвь', N'овощь', N'оранжевый', 41),
--(N'лук', N'овощь', N'зеленый', 40),
--(N'яблоко', N'фрукт', N'красный', 52),
--(N'банан', N'фрукт', N'желтый', 89),
--(N'помидор', N'овощь', N'желтый', 18)